version: "3"
services:
  serviceregistry:
    image: isharani21/claritypluspackage_backend:springCloud_v3 
    container_name: serviceregistry
    ports:
      - "8761:8761"
    networks:
      - packagemgmt-network
  
  apigateway:
    image: isharani21/claritypluspackage_backend:APIgateway_v3 
    container_name: apigateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    ports:
      - "9003:9003"
    networks:
      - packagemgmt-network 
    depends_on:
      - serviceregistry
  
  orderservice:
    image: isharani21/claritypluspackage_backend:order_v3
    container_name: orderservice
    ports:
      - "9001:9001"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://orderdatabase/Order_Service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - packagemgmt-network
    depends_on:
      - serviceregistry
      - apigateway
      - orderdatabase

  orderdatabase:
    image: mysql
    container_name: orderdatabase
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Order_Service
    volumes:
      - orderdatabase:/var/lib/mysql
    networks:
      - packagemgmt-network
  
  recipientservice:
    image: isharani21/claritypluspackage_backend:recipient_v3
    container_name: recipientservice
    ports:
      - "9002:9002"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://recipientdatabase/Recipient_Service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - packagemgmt-network
    depends_on:
      - serviceregistry
      - apigateway
      - recipientdatabase

  recipientdatabase:
    image: mysql
    container_name: recipientdatabase 
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Recipient_Service
    volumes:
      - recipientdatabase:/var/lib/mysql
    networks:
      - packagemgmt-network

  frontend:
    image: isharani21/claritypluspackage:frontend_v3  
    ports:
      - "3000:3000"
    networks:
      - packagemgmt-network

networks:
  packagemgmt-network:
    # name: packagemgmt-network

volumes:
  orderdatabase:
  recipientdatabase:
